apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lxd-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.71.212.60-10.71.212.89

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lxd-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - lxd-pool
