apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: devstack-deployments
  namespace: fleet-local
spec:
  repo: https://$GH_TOKEN@github.com/ross-ethridge/devstack.git
  branch: main
  paths:
    - kubernetes/mcps
    - kubernetes/minio
